---
# Items with `tags` below are only installed when one of their tags is passed with --tags
active_tags: "{{ (ansible_run_tags | list) | difference(ansible_skip_tags | list) }}"

homebrew_packages:
  - name: bat
  - name: btop
    tags: [optional]
  - name: curl
  - name: delta
    tags: [optional]
  - name: eza
  - name: file
  - name: fzf
  - name: git
  - name: htop
  - name: lazygit
    tags: [optional]
  - name: mise
    tags: [optional, mise]
  - name: neovim
    tags: [optional, neovim]
  - name: nmap
    tags: [optional]
  - name: ripgrep
  - name: stow
  - name: tree-sitter-cli
    tags: [optional, neovim]
  - name: tree
  - name: unzip
  - name: wget
  - name: zip
  - name: zoxide
