---
- name: Setup system
  hosts: localhost
  connection: local

  tasks:
    - name: Run common (Debian/Ubuntu)
      ansible.builtin.include_tasks: tasks/common.debian.yml
      when: ansible_facts["os_family"] == "Debian"

    - name: Run common (Mac OSX)
      ansible.builtin.include_tasks: tasks/common.macos.yml
      when: ansible_facts["os_family"] == 'Darwin'
