[tools]
node = { version = "24", postinstall = "npm i -g corepack && corepack prepare pnpm@latest-10" }
bun = "latest"
deno = "latest"
python = "latest"
uv = "latest"
rust = "latest"
zig = "latest"
java = "temurin"
go = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
python.uv_venv_auto = true
windows_shim_mode = "symlink"

[env]
# UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }
