[tools]
node = "24"
pnpm = "latest"
bun = "latest"
deno = "latest"
python = "latest"
uv = "latest"
rust = "latest"
java = "temurin"
go = "latest"

[settings]
pin = true
not_found_auto_install = false
task.run_auto_install = false

idiomatic_version_file_enable_tools = ["node"]
idiomatic_version_file_disable_files = ["node:package.json"]

python.uv_venv_auto = "create|source"

[env]
_.path = ['{{config_root}}/node_modules/.bin']
